### ISSUE TITLE
ФИКС: Групповые бейджи к мобильном брейкпоинте - пагинация скрыта футером

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#265]

**Comment by vconst** [comment]
Взял Александр

**Comment by YanaMit** [comment]
1. 7 групповых бейджей под ролью "руководитель локации" видно без проблем - ок.
2. две страницы групповых бейджей под ролью "админ" так же видно, переход между страницами по клику на нумерацию страниц успешен - ок.
