### ISSUE TITLE
column chooser

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#282]
Дизайн - https://www.figma.com/design/eKbWiaIWFuy4MWb3SmPclu/%D0%9A%D0%BE%D1%80%D0%BC%D0%B8%D1%82%D0%B5%D0%BB%D1%8C-2024?node-id=630-82796&node-type=frame&t=AFca0cGj9nK6N36A-0

Необходимо реализовать возможность скрытия/показа колонок в таблице волонтеров.
Реализуем по макетам, кроме кнопки выбрать все и кроме кнопок редактирования и добавления кастомных колонок.
По умолчанию видимость должны быть видимы колонки: Имя на бейдже, Имя, Фамилия, Службы/Локации, Статус, Бан, Кухня, Комментарий.
Состояние видимости колонок должно сохраняться в localStorage и подгружаться из localStorage при отображении таблицы.

**Comment by vconst** [comment]
Катя: у волонтера должна быть возможность выбрать из списка столбцы для отображения под его задачу

**Comment by VooDoo4815** [comment]
>Реализуем по макетам, кроме кнопки выбрать все и кроме кнопок редактирования и добавления кастомных колонок.  
Кнопку редактирования оставил, но она, как и раньше, ведёт на страницу создания кастомной колонки

**Comment by YanaMit** [comment]
1. по умолчанию "статус" не был у меня отмечен, по ТЗ должен быть.
![image](https://github.com/user-attachments/assets/ce5e1387-da3c-45d4-8146-1a7eb7dcccbd)
2. когда выбрала все колонки - у меня не получается промотать в бок, видно только то, что помещается на страницу: не вижу снизу бегунок в бок
![image](https://github.com/user-attachments/assets/9db54013-2b05-401b-96ea-03faa9612a95)
3. просто отмечаю - если снять все галочки -0 не пустая выдача, а равно ситуации, когда выбраны все поля.
4. кнопка "сохраненные таблицы" у меня серым , ничего с ней не могу сделать (админ) - это ок?
5. выгрузка в эксель выгружает все, а не только выбранные колонки - это ок?
6. фильтры пока по-старому. принципиальная разница в фильтрах - кнопка выбрать ве (еще нет) и фильтры в одну линию, скролл, если много? или еще что-то?

пройдено успешно - 
7. кнопка "добавить колонку" ведет на страницу кастомных полей (где можно добавить новое кастомное поле) - ок
8. при переходе на др страницу, а затем возврате - выбранные колонки сохраняются (фильтр сохраняется) - ок
9.  редактирование и выбрать все -пока отсутствует  - ок

**Comment by VooDoo4815** [comment]
1 - ок, поправлю
2 - полоса прокрутки находится внизу таблицы, там, где переход на другие страницы
3 - решил так сделать, т.к. не могу представить ситуации, когда нужно ничего не показывать
4 - да, это на будущее, пока что не реализовано, добавил, т.к. было в макете
5 - Мне кажется, что ок, в экселе и ненужные колонки можно удалить. Или кому-то какие-то поля нельзя видеть?
6 - в ТЗ про фильтры не написано. Какие изменения ожидаются?

**Comment by YanaMit** [comment]
2. полосу нашла, спасибо 
5. вроде бы, в ексель будет выбор, наверное, реализовываться будет позже (ну или я неправильно понимаю пока картинку), уточню на встрече:
![image](https://github.com/user-attachments/assets/6ec3be0b-eb77-47ae-afea-9a702ac71864)
6. это, скорее, вопрос, на будущее, нашла это в фигме, как раз тоже думаю, какие именно принципиальные изменения ожидаются.
вот тут увидела:
![image](https://github.com/user-attachments/assets/1f36874f-8c4d-42e5-a61a-5b8fba359617)

**Comment by YanaMit** [comment]
теперь ок
![image](https://github.com/user-attachments/assets/b12b105a-2ea2-41a1-a766-8a3685322fb8)
