### ISSUE TITLE
Добавить в раздел волонтеров информацию о числе волонтеров на поле

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#298]

**Comment by vconst** [comment]
Катя:

Если значение “сегодня” входит в диапазон “от-до” волонтера, то этот волонтер участвует в подсчете

**Comment by vconst** [comment]
More_Imen:

“Кол-во волонтеров: ххх” есть,  дважды (это удобно): под фильтрами, рядом с кнопкой “Кастомные поля” и внизу страницы после списка волонтеров. В документацию внесла.

**Comment by kori4k** [comment]
Есть воркэраунд, кастомными полями число "на поле можно вытащить"
