### ISSUE TITLE
В историю питания в карточке волонтера добавить столбец 0/1 - была ли выдана порция

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#303]

**Comment by vconst** [comment]
Катя:

сейчас если "даты активности не совпадают", то вне зависимости от нажатия кнопки в историю в админку запишется одинаковая инфа

типа неважно, покормили в долг или отказали.

**Comment by YanaMit** [comment]
я, наверное, не очень понимаю, суть доработки пока, у меня все по-прежнему, смотрю под админом. История питания. (волонтер Дамблдор) Кол-во порций - 5, по факту выдано было 3.
![image](https://github.com/user-attachments/assets/e861389a-7bf5-4175-a651-c2df37b089ca)

**Comment by JohnImril** [comment]
на скрине видно, что было выдано 2, и оно вот тут в таблице, но там еще не привязан бэк, тогда добавлю и в эту таблицу (я её до этого не заметил). И в результате должно отображаться только 2 порции, которые без ошибок?
![image](https://github.com/user-attachments/assets/dac51c2e-dca7-41e6-8476-227c1eb76493)

**Comment by YanaMit** [comment]
перепроверено - ок, теперь все верно.
единственное что - если волонтеру искусственно через создание кормления (не сканированием бейджа) добавить больше 1 порции - они корректно учтутся в строке "Результат: n порций", но в самой таблице не очень ясно, в которео кормление была не одна порция, а больше. Но в тз по этому поводу ничего не сказано. по тз все работает корректно.
