### ISSUE TITLE
если менять даты или статусы, а затем - кастомные поля, то кнопка сохранить не сработает на статус (автосэйв?)

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#322]

**Comment by YanaMit** [comment]
1. сменила статус и дату отъезда
2. проставила чек боксы рация,велик и еще парочку
3. нажала сохранить - автоматический переход к списку волонтеров
4. нажала обновить - в списке волонтеров у этого волонтера дата и статус обновились
5. захожу в карточку волонтера **- отметки в кастомных полях не сохранились. (**и один раз даже куда-то пропал qr, но снова воспроизвести получилось 1 раз, случайно, от чего зависит - не понимаю), **при этом в списке волонтеров все ок - поля есть, отмечено в них то, что отмечала и изменения сохранены, в истории на волонтере - тоже отметки в кастомных полях сохранены.**

видео: https://disk.yandex.ru/i/gpLQELwsVHKUgQ

**Comment by YanaMit** [comment]
проблема или нет - не знаю, но вопрос совпадает с описанным тут https://github.com/Insomnia-IT/feed/issues/326, поэтому пока не закрываю.

**Comment by YanaMit** [comment]
заведена задача https://github.com/Insomnia-IT/feed/issues/417
