### ISSUE TITLE
добавить в моб.админку кастомные поля (например, браслеты) которые юзает обычная админка (не обязательно все)

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#326]
В модель кастомных полей на беке добавлено поле mobile - https://github.com/Insomnia-IT/feed/pull/338
Кастомные поля с полем mobile равным true нужно показывать в мобильной админке в детальной карточке волонтера. 
В большой админке при создании и редактировании кастомных полей отобразить и давать редактировать поле mobile. Отображать его как "Показывать в мобильной админке?"

**Comment by vconst** [comment]
карточка дубль с описанием от кати: https://github.com/orgs/Insomnia-IT/projects/3/views/1?pane=issue&itemId=82236754

**Comment by vconst** [comment]
Александр взял

**Comment by YanaMit** [comment]
1. в большой админке возможность проставить чекбокс  "Показывать в мобильной админке?" есть
2. захожу в моб админке под ролью "руководитель локации"
   2.1. в фильтре есть и кастомные поля с проставленной галкой, и без нее. Как я понимаю, должны быть только с галкой "Показывать в мобильной админке?" - не ок
  2.2. в карточке волонтера вообще не виден раздел "кастомные поля" - не ок

в папке скрины (моб тел - ios и винд.10) и запись экрана с моб. телефона (ios 17.6.1)
https://disk.yandex.ru/d/R2Rk4jjCCEumwg

**Comment by vconst** [comment]
В фильтрах решили показывать все кастомные поля для руководителей локаций. По отображению сделали фикс.

**Comment by YanaMit** [comment]
1. по отображению - ок, руководитель локации, заходя в карточку волонтера видит только те кастомные поля, у которых есть галка "отображать в мобильной админке", 
2. но с сохранением у кастомных полей все-таки не очень. Вряд ли это относится к этой задаче, так как одинаковая проблема и в веб версии, и в мобильной. Кажется, где-то  описывала уже, но продублирую - 
шаги: 
- я захожу в волонтера, меняю ему значения в кастомных полях, 
- сохраняю, 
- в списке волонтёров обновляюсь, в таблице списка волонтеров новые значения кастомных полей по этому волонтеру отображаются, по ним все успешно фильтруется, 
НО! 
-  захожу в карточку волонтера - там во всех полях пустота.
- видео:
запись экран, моб версия - https://disk.yandex.ru/i/9Whsth3spgUirw
веб - https://disk.yandex.ru/i/fmR4Ei4RDXy6Jw

**Comment by YanaMit** [comment]
Перепроверила, пока все по-прежнему. Будем править?
