### ISSUE TITLE
В таблицу групповых бейджей и карточку ГБ добавить инфо о количестве волонтеров в нем.

### ISSUE THREAD

**Issue by kori4k** [Insomnia-IT/feed#344]
1) в таблицу грубовых бейджей добавить столбец, в котором отобразить число волонтеров в бейдже. Столбец назвать "Содержит волонтеров"
2) в карточке группового бейджа над списком волонтеров отражать число формата текстовой строки "В бейдже N волонтеров"

https://github.com/Insomnia-IT/feed/pull/366

**Comment by vconst** [comment]
В https://github.com/Insomnia-IT/feed/issues/368 добавил поле volunteer_count на беке, так как фронт долго грузит волонтеров и лишние запросы

**Comment by vconst** [comment]
https://github.com/Insomnia-IT/feed/pull/366

**Comment by YanaMit** [comment]
1. по функционалу ок, но есть опечатка "**### Количестиво** волонтеров: 21"
2. + есть странность с кэшированием. до обновления страницы показывается не всегда верное кол-во волонтеров. не всегда воспроизводится. Видео, где воспроизвелось, прикладываю. https://disk.yandex.ru/i/l8HG3ZggBiRA8A
После обновления страницы все ок.

**Comment by YanaMit** [comment]
1. функционал ок, опечатка исправлена.
2. по кэшированию все-таки когда как, но это у нас по многим пунктам так, то есть вряд ли это связано с задачей.
примеры на скринах:
https://disk.yandex.ru/i/ZrqAqlRwmAXe5A
https://disk.yandex.ru/i/uZYspsN8m5vsrA
https://disk.yandex.ru/i/ciBAtxn25QsxIw

**Comment by VooDoo4815** [comment]
@YanaMit а какой сценарий? Это создание нового бейджа или добавление в существующий?

**Comment by YanaMit** [comment]
> @YanaMitа какой сценарий? Это создание нового бейджа или добавление в существующий?

это было добавление в существующий

**Comment by YanaMit** [comment]
крайне редко воспроизводится (1 из 6 раз). можно закрывать?

**Comment by VooDoo4815** [comment]
Давай закроем
