### ISSUE TITLE
Скрыть логин по имени и паролю под кнопку

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#350]

**Comment by YanaMit** [comment]
логин и пароль скрыты под кнопку - ок.
заметила особенность - при переходе по ссылке https://srv.rumyantsev.com/
сначала показывается на секунду вот такой экран
![Image](https://github.com/user-attachments/assets/b74a6e5e-b417-4845-9ef2-f18e9c3cc3e4)
, затем уже экран входа, при переходе по ссылке https://srv.rumyantsev.com/login 
такого нет, все сразу ок.
