### ISSUE TITLE
БАГ: при занесении в ГБ людей по одному сохраняется только последний

### ISSUE THREAD

**Issue by kori4k** [Insomnia-IT/feed#400]
При наполнении группового бейджа появляется список волонтеров и чекбоксы около каждого. Если занести несколько человек и нажать кнопку сохранения, то в ГБ будут добавлены все. А если добавить одного и заново открыв список добавить еще - сохранится только последняя итерация.
Ожидаемое - при добавлении волонтеров по одному через несколько открытий списка и нажатию кнопки "сохранить" после всех итераций сохранятся все добавленные волонтеры.

Шаги воспроизведения: 
1. Создать бейдж
2. Открыть бейдж на редактирование, нажать "добавить волонтера", найти по ФИО и нажать "ок" (он попадает в список)
3. Снова нажать "добавить волонтера", выбрать человека и нажать ОК (он попадает в список)
4. Нажать "сохранить" (сохранятся не оба, а последний)

Видео для понимания - https://disk.yandex.ru/i/bhzyZOxfXV2pjg

**Comment by VooDoo4815** [comment]
https://github.com/Insomnia-IT/feed/pull/402

**Comment by YanaMit** [comment]
проверено, не воспроизводится.
