### ISSUE TITLE
Эндпоинт по рассчету стастики в django backend'е

### ISSUE THREAD

**Issue by vconst** [Insomnia-IT/feed#64]

**Comment by Novartole** [comment]
- [PR](https://github.com/Insomnia-IT/feed/pull/52) для отображения статистики в админке
- используемый там [mock](packages/admin/src/components/entities/statistic/lib/mock.ts)
- [калькуляция статистики](packages/scanner/src/request-local-db/use-local-stats.ts) в scanner
- [калькуляция статистики](https://github.com/Insomnia-IT/yclins/blob/7702e02b7cc5b2377e5d1fa7faae3d01b44eeea3/app/__init__.py#LL538C38-L538C38) в yclins

**Comment by Novartole** [comment]
Пример нового контракта:
{
    '2023-04-24 00:00:00': {
        plan: {
            morning: {
                мясоед: 0,
                веган: 0
            },
            lunch: {
                мясоед: 0,
                веган: 0
            },
            dinner: {
                мясоед: 0,
                веган: 0
            },
            night: {
                мясоед: 0,
                веган: 0
            }
        },
        fact: {
            morning: {
                мясоед: 0,
                веган: 2
            },
            lunch: {
                мясоед: 0,
                веган: 2
            },
            dinner: {
                мясоед: 0,
                веган: 2
            },
            night: {
                мясоед: 0,
                веган: 2
            }
        }
    }
}

Решили, что тоталы из старой версии (totalCount, totalCountPlanned, total) можно убрать, так как они излишние, и считать эти суммы вместо этого по данным на клиенте. Объект plan - план по алгоритму выше, fact - фактические данные по транзакциям.
